package com.elorserv.model;
// Generated 23 ene 2026, 13:27:32 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Ciclos generated by hbm2java
 */
@Entity
@Table(name = "ciclos")
public class Ciclos implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Column
	private String nombre;
	
	/*
	@ManyToOne(fetch = FetchType.LAZY) // Lazy para que no cargue el tipo si no lo pides
    @JoinColumn(name = "id")
	private Modulos modulos;
	*/
	
	@OneToMany(mappedBy = "ciclos")
	private Set<Matriculaciones> matriculaciones;

	public Ciclos() {
	}

	public Ciclos(String nombre) {
		this.nombre = nombre;
	}

	public Ciclos(String nombre, Modulos modulos, Set<Matriculaciones> matriculaciones) {
		this.nombre = nombre;
		//this.modulos = modulos;
		this.matriculaciones = matriculaciones;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/*
	public Modulos getModuloses() {
		return this.modulos;
	}

	public void setModuloses(Modulos moduloses) {
		this.modulos = moduloses;
	}
	*/

	public Set<Matriculaciones> getMatriculacioneses() {
		return this.matriculaciones;
	}

	public void setMatriculacioneses(Set<Matriculaciones> matriculacioneses) {
		this.matriculaciones = matriculacioneses;
	}
	
}
