package com.elorserv.model;
// Generated 21 ene 2026, 14:14:16 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Tipos generated by hbm2java
 */
@Entity
@Table(name = "tipos")
public class Tipos implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Column
	private String name;
	
	@Column
	private String nameEu;
	
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipos")
	private Set<Users> userses = new HashSet(0);
	*/

	public Tipos() {
	}

	public Tipos(String name) {
		this.name = name;
	}

	public Tipos(String name, String nameEu, Set userses) {
		this.name = name;
		this.nameEu = nameEu;
		//this.userses = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameEu() {
		return this.nameEu;
	}

	public void setNameEu(String nameEu) {
		this.nameEu = nameEu;
	}

	/*
	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}
	*/
	
}
